---
name: RRD-Simple
version: 1.41
author:
  - Nicola Worthington <nicolaw@cpan.org>
abstract: Simple interface to create and store data in RRD files
license: open_source
requires:
  Carp: 0
  File::Basename: 0
  File::Copy: 0
  File::Spec: 0
  File::Temp: 0
  POSIX: 0
  RRDs: 0
recommends:
  Test::Deep: 0.093
  Test::Pod: 1.2
  Test::Pod::Coverage: 1.06
build_requires:
  Test: 0
  Test::More: 0
conflicts:
  RRDTool::Managed: 0
provides:
  RRD::Simple:
    file: lib/RRD/Simple.pm
    version: 1.41
  RRD::Simple::Examples:
    file: lib/RRD/Simple/Examples.pm
  RRD::Simple::_Colour:
    file: lib/RRD/Simple.pm
    version: 1.41
generated_by: Module::Build version 0.2611
